<a href="https://colab.research.google.com/github/JWKANG0308/Pytorch_tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensors**



*   A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's
*   default data type of float32
*   More suitable for deep learning than a numpy array





In [2]:
import numpy
import torch

**Lists**

In [9]:
list1 = [[1,2,3,4,5],[6,7,8,9,10]]
print(list1)
type(list1)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


list

**Numpy**

In [12]:
numpy1= numpy.random.rand(2,5)
print(numpy1, numpy1.dtype)
type(numpy1)


[[0.3835115  0.01868531 0.00444466 0.96107931 0.74982357]
 [0.9130665  0.94045055 0.37327858 0.12080764 0.07790235]] float64


numpy.ndarray

**Tensors**

In [22]:
tensor_2d= torch.randn(2,5) # randn : Values are drawn from a standard normal distribution (mean = 0, standard deviation = 1).
tensor_2d

tensor([[ 0.0555,  0.3879,  1.0726, -0.3437,  1.0889],
        [ 1.2168,  1.9033,  0.2477, -0.8990, -0.1238]])

In [26]:
tensor_3d = torch.randn(3,2,5)
tensor_3d, tensor_3d.dtype

(tensor([[[-2.2816,  0.0286,  1.2975, -0.5155,  2.1422],
          [ 0.1095, -0.1316, -1.9421, -1.0233,  1.8790]],
 
         [[-0.2232, -1.8280,  0.3033, -0.8597,  0.5618],
          [ 0.2299,  0.6161,  0.0106, -0.9270, -1.0820]],
 
         [[ 0.3908, -0.2625,  1.9624, -2.0838,  0.3664],
          [-0.1483,  2.0116,  2.3205,  0.7566,  0.2969]]]),
 torch.float32)

In [27]:
tensor_from_numpy = torch.tensor(numpy1)
tensor_from_numpy, tensor_from_numpy.dtype  #dtype = flaot64 because tensor is created from the numpy

(tensor([[0.3835, 0.0187, 0.0044, 0.9611, 0.7498],
         [0.9131, 0.9405, 0.3733, 0.1208, 0.0779]], dtype=torch.float64),
 torch.float64)