<a href="https://colab.research.google.com/github/JWKANG0308/Pytorch_tutorial/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
tensor1 = torch.arange(10)
tensor1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(tensor1.reshape(2,5))
print(tensor1.reshape(2,-1))
print(tensor1.reshape(-1,5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [4]:
tensor2 = torch.rand(2,5)
print(tensor2.shape)
reshpaed_tensor2 = tensor2.reshape(1,-1)
print(reshpaed_tensor2.shape)
print(tensor2.shape)

torch.Size([2, 5])
torch.Size([1, 10])
torch.Size([2, 5])


In [5]:
tensor3 = torch.arange(15)
tensor3 = tensor3.reshape(5,3)
tensor3

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [6]:
tensor3[:,1:2]

tensor([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]])

Math Operations

In [7]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])



In [8]:
torch.add(tensor_a,tensor_b) # addition

tensor([ 6,  8, 10, 12])

In [9]:
torch.sub(tensor_b,tensor_a) # subtraction

tensor([4, 4, 4, 4])

In [10]:
torch.mul(tensor_a,tensor_b) # multiplication

tensor([ 5, 12, 21, 32])

In [11]:
torch.div(tensor_b,tensor_a) # division

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
torch.remainder(tensor_b,tensor_a) # remainder

tensor([0, 0, 1, 0])

In [13]:
tensor_a.add_(tensor_b) # addition reassignment
tensor_a

tensor([ 6,  8, 10, 12])